version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
#    python: "mambaforge-22.9"

#conda:
#  environment: docs/environment.yml

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
